[server]
hostname = "192.168.104.82"
node_ip = "127.0.0.1"
server_role = "traffic-manager"
offset=0

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"



#[[apim.event_hub.publish.url_group]]
#urls = ["tcp://cpl1:9611", "tcp://cpl2:9611"]
#auth_urls = ["ssl://cpl1:9711", "ssl://cpl2:9711"]


# Event Listener configurations
[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

# https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated/
[event_listener.properties]
notification_endpoint = "https://192.168.104.82:5000/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "default"



# Event Hub configurations
[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://192.168.104.82:5000/services/"
event_listening_endpoints = ["tcp://192.168.104.82:5672", "tcp://192.168.104.82:5673"]

[[apim.event_hub.publish.url_group]]
urls = ["tcp://192.168.104.82:9611", "tcp://192.168.104.82:9612"]
auth_urls = ["ssl://192.168.104.82:9711", "ssl://192.168.104.82:9712"]

[apim.key_manager]
service_url = "https://192.168.104.82:9483/services/"
type = "WSO2-IS"
#username = "$ref{super_admin.username}"
#password = "$ref{super_admin.password}"
#pool.init_idle_capacity = 50
#pool.max_idle = 100
#key_validation_handler_type = "default"
#key_validation_handler_type = "custom"
#key_validation_handler_impl = "org.wso2.carbon.apimgt.keymgt.handlers.DefaultKeyValidationHandler"


# adding GW environments (if they are not added here, tm will throw errors)
# tm2_1        | [2022-03-09 04:40:27,690] ERROR - GlobalThrowableMapper Configured read only environment not found: GW2
# Gateway configuration
[[apim.gateway.environment]]
name = "GW1"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "https://gw1:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://gw1:9099"
wss_endpoint = "wss://gw1:8099"
http_endpoint = "http://gw1:8280"
https_endpoint = "https://gw1:8243"

[[apim.gateway.environment]]
name = "GW2"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "https://gw2:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://gw2:9099"
wss_endpoint = "wss://gw2:8099"
http_endpoint = "http://gw2:8280"
https_endpoint = "https://gw2:8243"



[apim.throttling]
service_url = "https://192.168.104.82:4000/services/"
throttle_decision_endpoints = ["tcp://tm1:5672", "tcp://tm2:5672"]
event_duplicate_url = ["tcp://tm1:5672"] 
enable_data_publishing = true
enable_policy_deploy = true
enable_blacklist_condition = true
enable_persistence = true


[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm1:9611"]
traffic_manager_auth_urls=["ssl://tm1:9711"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm2:9611"]
traffic_manager_auth_urls=["ssl://tm2:9711"]

