[server]
hostname = "gw.wso2.com"
node_ip = "127.0.0.1"
server_role = "gateway-worker"
offset=0

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# Key Manager configuration
[apim.key_manager]
service_url = "https://192.168.104.82:9483/services/"
username = "admin"
password = "admin"
type = "WSO2-IS"

# Traffic Manager configurations
[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
enable_data_publishing = true
enable_policy_deploy = true
enable_blacklist_condition = true
enable_persistence = true
service_url = "https://192.168.104.82:4000/services/"
throttle_decision_endpoints = ["tcp://tm1:5672", "tcp://tm2:5672"]


[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm1:9611"]
traffic_manager_auth_urls=["ssl://tm1:9711"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm2:9611"]
traffic_manager_auth_urls=["ssl://tm2:9711"]

# Event Listener configurations
[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

# https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated/
[event_listener.properties]
notification_endpoint = "https://192.168.104.82:5000/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "default"



# Event Hub configurations
[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://192.168.104.82:5000/services/"
event_listening_endpoints = ["tcp://192.168.104.82:5672", "tcp://192.168.104.82:5673"]

[[apim.event_hub.publish.url_group]]
urls = ["tcp://192.168.104.82:9611", "tcp://192.168.104.82:9612"]
auth_urls = ["ssl://192.168.104.82:9711", "ssl://192.168.104.82:9712"]

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
allow_credentials = false

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["GW1" , "GW2"]


[apim.analytics]
enable = true
config_endpoint = "https://analytics-event-auth.choreo.dev/auth/v1"
auth_token = "1943b090-fe0a-4053-8ccc-16580ffdaa5d"